<?php
    $a = 1+2+3;
    echo ("Сумма чисел " . $a);
    echo "<br>";
    echo 1+2+3;
    echo "<br>";
    $a = 10;
    $b = 2;
    echo ("Сумма = " . ($a + $b) . " Разность = " . ($a - $b) . " Произведение = " . ($a * $b) . " Частное = " . ($a / $b));
    echo "<br>";
    $c = 10;
    $d = 5;
    $result = $c + $d;
    echo $result;
    echo "<br>";
    $a = 1;
    $b = 2;
    $c = 3;
    echo ($a + $b + $c);
    echo "<br>";
    $a = 10;
    $b = 5;
    $c = $a - $b;
    $d = 7;
    $result = $c + $d;
    echo $result;
    echo "<br>";
    $a = 1.5;
    $b = 0.75;
    echo $a + $b;
    echo "<br>";
    $a = -100;
    echo $a;
    echo "<br>";
    $a = 15;
    echo ("Обратное число от $a это " .-$a);
    echo "<br>";
    $a = 10;
    $b = 3;
    echo ("Остаток от деления " . $a % $b);
    echo "<br>";
    echo ("Возведение в степень результат " . 2 ** 10);
    echo "<br>";


